name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ cmake make libgtest-dev

    - name: Build
      run: |
        make

    - name: Run tests
      run: |
        make test
        ./test-ASCII85_app